# Generated by Django 5.2.7 on 2025-12-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_push_notifications_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_sound_enabled',
            field=models.BooleanField(default=True, help_text='Play sound for new messages'),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Enable push notifications for new messages'),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_push_subscription',
            field=models.JSONField(blank=True, help_text='Web Push API subscription data', null=True),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='users',
        ),
    ]
