# Generated by Django 5.2.7 on 2025-12-16 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_pet_is_available_for_breeding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_unlocked', models.BooleanField(default=True)),
                ('pet1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet1', to='pets.pet')),
                ('pet2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pet2', to='pets.pet')),
            ],
            options={
                'db_table': 'breeding_matches',
            },
        ),
        migrations.CreateModel(
            name='BreedingChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='breeding.breedingmatch')),
            ],
            options={
                'db_table': 'breeding_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreedingSwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to='pets.pet')),
                ('user_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to='pets.pet')),
            ],
            options={
                'db_table': 'breeding_swipes',
            },
        ),
        migrations.AddIndex(
            model_name='breedingmatch',
            index=models.Index(fields=['pet1', 'pet2'], name='breeding_ma_pet1_id_8a2417_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingmatch',
            index=models.Index(fields=['created_at'], name='breeding_ma_created_0dd507_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breedingmatch',
            unique_together={('pet1', 'pet2')},
        ),
        migrations.AddIndex(
            model_name='breedingchatmessage',
            index=models.Index(fields=['match', 'created_at'], name='breeding_ch_match_i_0154c8_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingchatmessage',
            index=models.Index(fields=['sender', 'read'], name='breeding_ch_sender__71c101_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingswipe',
            index=models.Index(fields=['user_pet', 'action'], name='breeding_sw_user_pe_c743ad_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingswipe',
            index=models.Index(fields=['target_pet', 'action'], name='breeding_sw_target__f07152_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingswipe',
            index=models.Index(fields=['created_at'], name='breeding_sw_created_2ea3b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breedingswipe',
            unique_together={('user_pet', 'target_pet')},
        ),
    ]
