# Generated by Django 5.2.7 on 2025-12-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_available_for_breeding',
            field=models.BooleanField(default=False),
        ),
    ]
