# Generated by Django 5.2.7 on 2025-12-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
