# Generated by Django 5.2.7 on 2026-01-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_onlineuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
