# Generated by Django 5.2.7 on 2025-12-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=500)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('read_time', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('search_query', models.CharField(db_index=True, max_length=200)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('times_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'education_article_cache',
                'ordering': ['-relevance_score', '-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='education_a_categor_f27b04_idx'), models.Index(fields=['search_query', '-relevance_score'], name='education_a_search__b1afd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_id', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('search_query', models.CharField(db_index=True, max_length=200)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('times_viewed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'education_video_cache',
                'ordering': ['-relevance_score', '-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='education_v_categor_b6d2c6_idx'), models.Index(fields=['search_query', '-relevance_score'], name='education_v_search__7b3cfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='education.articlecache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_user_article_views',
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='education_u_user_id_c86afd_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='UserVideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='education.videocache')),
            ],
            options={
                'db_table': 'education_user_video_views',
                'indexes': [models.Index(fields=['user', '-watched_at'], name='education_u_user_id_12057e_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='education.articlecache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='education.videocache')),
            ],
            options={
                'db_table': 'education_user_bookmarks',
                'indexes': [models.Index(fields=['user', 'content_type', '-created_at'], name='education_u_user_id_a4b8a6_idx')],
            },
        ),
    ]
