# Generated by Django 6.0.1 on 2026-02-05 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Breed name (e.g., 'Golden Retriever', 'Persian')", max_length=200)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('rabbit', 'Rabbit'), ('other', 'Other')], db_index=True, help_text='Animal species', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description from Wikipedia')),
                ('origin', models.CharField(blank=True, help_text='Country/region of origin', max_length=200)),
                ('wikipedia_url', models.URLField(blank=True, help_text='Wikipedia page URL', validators=[django.core.validators.URLValidator()])),
                ('life_span', models.CharField(blank=True, help_text="Life span (e.g., '10-12 years')", max_length=50)),
                ('temperament', models.TextField(blank=True, help_text='Temperament/personality traits')),
                ('weight', models.CharField(blank=True, help_text="Weight range (e.g., '25-35 kg')", max_length=100)),
                ('height', models.CharField(blank=True, help_text="Height range (e.g., '55-60 cm')", max_length=100)),
                ('main_image', models.URLField(blank=True, help_text='Primary breed image URL', validators=[django.core.validators.URLValidator()])),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Array of image URLs for gallery')),
                ('youtube_videos', models.JSONField(blank=True, default=list, help_text='Array of video objects: [{title, youtube_id, thumbnail}]')),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by admin')),
                ('api_fetch_count', models.IntegerField(default=0, help_text='Number of times data was fetched from APIs')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time data was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When breed was first added to DB')),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'db_table': 'breed_info',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['species', 'name'], name='breed_info_species_8adbfd_idx'), models.Index(fields=['last_updated'], name='breed_info_last_up_a90d1a_idx'), models.Index(fields=['is_verified'], name='breed_info_is_veri_0be9ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'species'), name='unique_breed_species')],
            },
        ),
    ]
