# Generated by Django 6.0.1 on 2026-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_alter_adoptionapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', max_length=20),
        ),
    ]
