# Generated by Django 6.0.1 on 2026-02-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorearnings',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid to doctor', max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorearnings',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='video_call_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
