# Generated by Django 6.0.1 on 2026-02-05 22:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-is_trending', '-rating']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_tren_5958d2_idx',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(blank=True, choices=[('', 'Not Food'), ('dry', 'Dry Food'), ('wet', 'Wet Food'), ('raw', 'Raw Food'), ('freeze_dried', 'Freeze Dried'), ('dehydrated', 'Dehydrated')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='grooming_type',
            field=models.CharField(blank=True, choices=[('', 'Not Grooming'), ('brush', 'Brush/Comb'), ('shampoo', 'Shampoo/Conditioner'), ('nail_care', 'Nail Care'), ('dental', 'Dental Care'), ('ear_care', 'Ear Care'), ('cologne', 'Cologne/Deodorizer')], max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='health_type',
            field=models.CharField(blank=True, choices=[('', 'Not Health Product'), ('supplement', 'Supplement'), ('medication', 'Medication'), ('flea_tick', 'Flea & Tick'), ('vitamins', 'Vitamins'), ('first_aid', 'First Aid')], max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size_suitability',
            field=models.CharField(choices=[('all', 'All Sizes'), ('small', 'Small (< 25 lbs)'), ('medium', 'Medium (25-50 lbs)'), ('large', 'Large (50-100 lbs)'), ('xlarge', 'Extra Large (> 100 lbs)')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='toy_type',
            field=models.CharField(blank=True, choices=[('', 'Not Toy'), ('interactive', 'Interactive'), ('plush', 'Plush/Soft'), ('chew', 'Chew Toy'), ('puzzle', 'Puzzle'), ('fetch', 'Fetch/Throw'), ('teaser', 'Teaser/Wand'), ('ball', 'Ball')], max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Product weight or pet weight range', max_length=50),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('treats', 'Treats'), ('toys', 'Toys'), ('grooming', 'Grooming'), ('health', 'Health & Medicine'), ('accessories', 'Accessories'), ('housing', 'Housing & Bedding'), ('training', 'Training'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='species',
            field=models.CharField(choices=[('all', 'All Pets'), ('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('small_pet', 'Small Pet')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sub_type',
            field=models.CharField(blank=True, help_text="e.g., 'dry', 'wet', 'interactive', 'plush'", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('all', 'All Ages'), ('puppy_kitten', 'Puppy/Kitten'), ('adult', 'Adult'), ('senior', 'Senior')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform_links',
            field=models.JSONField(blank=True, default=dict, help_text="Links to purchase platforms: {'amazon': 'url', 'chewy': 'url', ...}"),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Approximate price for reference', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='save_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('reptile', 'Reptile'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='General availability indicator'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suitable_breeds',
            field=models.JSONField(blank=True, default=list, help_text='List of breed names this product is suitable for'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Additional tags: ['grain-free', 'organic', 'usa-made', ...]"),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class name', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productview',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['food_type'], name='products_pr_food_ty_5b1317_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['toy_type'], name='products_pr_toy_typ_f855dc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating', '-review_count'], name='products_pr_rating_d24769_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user', '-created_at'], name='products_pr_user_id_5c2113_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', '-created_at'], name='products_pr_product_5c613d_idx'),
        ),
    ]
